### ISSUE TITLE
Clean and create subset of newest citation data for upload

### ISSUE THREAD

**Issue by gregpawin** [hackforla/lucky-parking#132]
Clean bad GPS coordinates and change projection. Also use 1% or less of data.

**Comment by gregpawin** [comment]
Talked to Matthew checked dataset. Coordinates were in the wrong projection. Sent him another old dataset and used Geopandas to save a geojson. Note: geojson do not like tuples. Saved it in the Google Drive folder.

**Comment by andy-vh** [comment]
Created .csv and .geojson files containing data from 07/01/2020 to 07/27/2020. Coordinates were converted using pyproj.
