### ISSUE TITLE
Get existing Mapbox code to repopulate map after repositioning and resizing map

### ISSUE THREAD

**Issue by gregpawin** [hackforla/lucky-parking#145]
### Overview
The current version of the Mapbox webapp works in a very limited way. Getting the functionality and usability of the code to display the citation data is a current priority. Currently the Mapbox webapp does not repopulate after repositioning or changing the zoom level. This needs to be addressed.
### Action items

- [ ] Get the code to refresh after repositioning or changing the zoom level of the webapp

### Resources/Instructions
- Reach out to Jake Mensche if necessary
- Collaborate with other team members

**Comment by samreality4** [comment]
Working on this issue right now.

**Comment by gregpawin** [comment]
Notes from Jake Mensch on 8/20/2020:
1. Layers and sources don't need to be removed to update the map
Currently the code is removing and then re-adding the 'places' source/layer
to the map every time there's a data update. That's probably what's causing the
flickering.
To avoid that, you can just add the sources and layers at the beginning,
after the 'load' event fires.
```
useEffect(() => {
  const map = new mapboxgl.Map({ /* init options * / })
  map.once("load", () => {
    // add all sources
    // add all layers
    // add all event listeners
    // add geocoder
    setMap(map);
    setMounted(true);
  });
}, []);
```
Then when you need to update the places, you can set the data on the
existing source instead of removing and re-adding it:
```
map.getSource('places').setData([ /* the new data */ ])
```
If you need to show/hide the layer, set the 'visibility' property instead
of removing/re-adding the layer.
```
map.setPaintProperty('places', 'visibility', 'visible')   // show
map.setPaintProperty('places', 'visibility', 'none')      // hide
```
2. API calls are probably to frequent.
The current code makes an API call every time the 'move' event fires, which
happens multiple time when you're panning or zooming. You could use the 'moveend'
event instead, so the map would only update when you've stopped panning/zooming.
3. not necessary to listen for 'render' events
In the update function, the data is being updated whenever the render event fires:
```
map.once('render' () => {
  // updating
})
```
The problem here is that the render event is firing multiple times per
api call, so the map is doing unnecessary updates. If you add the sources/layers
on load and then leave them alone (see above), you shouldn't have to wait
for the render event to update the data.

**Comment by mg78856** [comment]
[style reference](https://docs.mapbox.com/help/demos/heatmap/index.html)

**Comment by samreality4** [comment]
To avoid fetching too much on lat, long, zoom changes use "moveend" instead of "move":

map.on("moveend", () => {
      setLng(map.getCenter().lng.toFixed(4));

      setLat(map.getCenter().lat.toFixed(4));

      setZoom(map.getZoom().toFixed(2));
    });

**Comment by gregpawin** [comment]
Resolved via: https://github.com/hackforla/lucky-parking/pull/150
