### ISSUE TITLE
Add heat mapping of citation data

### ISSUE THREAD

**Issue by gregpawin** [hackforla/lucky-parking#162]
### Overview
Activate heat mapping of citation data. Heat maps make it easier to see relative densities of citations which overlapping data points do not show. Mapbox provides some sample code/tutorials. Other Hack4LA projects like 311 have demo heat map code.

### Action items
- [ ] Update code according to example/tutorial/other Hack4LA mapping project code
- [ ] Test locally
- [ ] Upload changes and spin up services to test on AWS

### Resources/Instructions
Check out Mapbox examples/tutorials: https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/

**Comment by JacobZwang** [comment]
my bad, merge had some duplicate code.
