### ISSUE TITLE
Dockerize webapp/master branch

### ISSUE THREAD

**Issue by gregpawin** [hackforla/lucky-parking#196]
### Overview
We need to dockerize Node.js and PostgreSQL so developers will work on the same environment and dependencies using the same containers.

### Action items
- [x] Dockerize Node.js
- [x] Dockerize PostgreSql
    - To maintain stability for the production's sql environment, we will only use the postgresql container when developing and testing locally. The prod and dev instances will still run sql without a docker container. 
- [x] Test that the new containers reflect the production environment when ran locally
- [x] Push the code to dev
- [x] Implement the dockerized Node.js on the dev instance, and ensure that the site's functionality stays the same
- [ ] Implement the dockerized Node.js on the prod instance, and ensure that the site's functionality stays the same
- [x] Edit our currently existing CI/CD workflow to incorporate the new docker containers.

### Resources/Instructions
Discuss with Greg

**Comment by macho-catt** [comment]
Postgresql is dockerized via this PR #343.
Next step is dockerizing node, then testing with another dev to see if they are able to run docker and have a working environment

**Comment by macho-catt** [comment]
Dockerized node in #344

**Comment by macho-catt** [comment]
Dev instance on aws now runs node on docker (postgres is still local).
Related prs:
#347 
#348 
#349

Since prod instance will get docker when a release branch is created, we can close this for now and open a new issue to dockerize the node on prod that is dependent on the release branch.
