### ISSUE TITLE
Create Wikipages about setting up developer environment

### ISSUE THREAD

**Issue by gregpawin** [hackforla/lucky-parking#221]
Resources:
[GitHub Guide on adding wiki pages](https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#adding-images)

**Comment by qiqicodes** [comment]
[Lucky Parking developer's contributing guide](https://github.com/hackforla/lucky-parking/wiki/Developer-Contributing-Guide/) is up and ready =]
