### ISSUE TITLE
Create Wiki pages about setting up developer environment for Lucky Parking Data Team

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#225]
### Overview
Create contributing doc for Lucky Parking Data Team so volunteers can contribute with no friction.

### Action Items
- [ ] Edit [Data Team Contributing Wiki Page](https://github.com/hackforla/lucky-parking/wiki/Data-Team-Contributing-Guide)

### Resources/Instructions
[Lucky Parking Developer Contributing Guide](https://github.com/hackforla/lucky-parking/wiki/Developer-Contributing-Guide)
[GitHub Guide on adding wiki pages](https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#adding-images)

**Comment by gregpawin** [comment]
Progress: Added more info to the [Data Team Contributing Guide](https://github.com/hackforla/lucky-parking/wiki/Data-Team-Contributing-Guide). Will add more info about the citation-analysis branch and other tools.
Blockers: Adding new environment setup tools. Will need to discuss with devs more.
Availability: I'll have a couple hours this week
ETA: Next month
Pictures (if necessary): None.

**Comment by gregpawin** [comment]
Progress: Will update pages with new Docker tools
Blockers: Needs more discussion with devs.
Availability: I'll have a couple hours this week
ETA: Next month
Pictures (if necessary): None.

**Comment by gregpawin** [comment]
Progress: [Docker tools here](https://github.com/hackforla/lucky-parking/wiki/Guide-to-Docker). Updated Wiki with starter code in [citation-analysis notebook folder](https://github.com/hackforla/lucky-parking/tree/citation-analysis/notebooks).
Blockers: Needs more discussion with devs.
Availability: I'll have a couple hours this week
ETA: Next month
Pictures (if necessary): None.

**Comment by gregpawin** [comment]
Wiki started here: https://github.com/hackforla/lucky-parking/wiki/Data-Team-Contributing-Guide
