### ISSUE TITLE
Complete Heuristic Analysis

### ISSUE THREAD

**Issue by salmonciara** [hackforla/lucky-parking#233]
Any UX/UI individual can complete a Heuristic Analysis of the current UX Parking Demo Site. This is an exception to the rule of only one individual assigning themselves to a tasks. 

This task will be due by next Monday, July 12th. It will be reviewed when we go into UX/UI break out room. 

Yen has a template for a Heuristic Analysis. Please get this from her so if you need a Heuristic Analysis template.

**Comment by simzou** [comment]
Yen's: https://docs.google.com/document/d/1zK17ISHJdxVZMMIK_crWE1_1vqJAUU53e6zAqq0Yq4I/edit
Ciara's: https://docs.google.com/document/d/1Q0ncsIIdkM8tBjtrBBMgxpA8rUvGKedc/edit

Other heuristic analysis artifacts are also in the drive under the UI/UX folder, currently titled "User Research"
