### ISSUE TITLE
Competitive Analysis

### ISSUE THREAD

**Issue by salmonciara** [hackforla/lucky-parking#237]

**Comment by simzou** [comment]
Looks like a duplicate of #242

**Comment by salmonciara** [comment]
@simzou 

Yen also completed an competitive analysis after I conducted mine. I believe to look at different aspects than I considered. 

You can find that here: https://docs.google.com/spreadsheets/d/15Z6VMJqTrps5G5g-dEY4iEPLjsTdKZ-YFQyrPp-zpU0/edit

This can stay closed though. Thank you for going through the board and cleaning it up!
