### ISSUE TITLE
Competitive Analysis on Mapping Websites

### ISSUE THREAD

**Issue by salmonciara** [hackforla/lucky-parking#242]
Conduct a Competitive Analysis on Mapping Websites

Find out pro/cons to current products. See where our product can fit into that product space. 

Present to cross-functional team with actions items from analysis.

**Comment by simzou** [comment]
@salmonciara I see you marked this issue as done, could you point to where the slides / report from the analysis was uploaded?

**Comment by salmonciara** [comment]
@simzou 

Here is the excel for the competitive analysis: https://docs.google.com/spreadsheets/d/1DESQPqqaOi_U1KxbSWEhadX1OM2bwtd1gUXYyhEuB_0/edit?resourcekey=0-ISKZfZn-_HtM1Pw3Ofgl2w

Here is the presentation deck: https://drive.google.com/file/d/19JMniP_LGrq6jRHuI6TZPqdifZ4CT98Q/view?usp=drivesdk (this was uploaded as a keynote, let me know if you need me to change it to a PDF so you can view it)

I do want to disclaim that this analysis was completed with the initial understanding that general LA citizen were the target users. That has pivoted to have the 'ideal' user to be city council members so this may not accurately reflect the market space we are trying to enter. 

Let me know if you have any other questions!

**Comment by simzou** [comment]
Thanks! I don't seem to have access to the spreadsheet though I did find this in our drive: https://docs.google.com/spreadsheets/d/1YYeFuJNz5x8li4shgB9ec4gR0mekV7h8jEg4uEbH8mo/edit#gid=0. Is it the same thing?

Cool, thanks for sharing the context of that analysis. I'm secretly hopeful that making this useful for a city council member and for a general citizen won't be _that_ different, but I guess we'll see.

**Comment by simzou** [comment]
Analysis uploaded to Drive folder here: https://docs.google.com/spreadsheets/d/19aH28pWjDFtXNFkZsSvkzvbsLlNEEkgHFZcNtkFJ2UQ/edit#gid=2069237634
