### ISSUE TITLE
Wireframe website

### ISSUE THREAD

**Issue by salmonciara** [hackforla/lucky-parking#248]
Wireframe

### Action Items

- [x] Add a Title/Description on top of Area Pie Charts pop-out.  E.g. “Info on ALL Citations and Ticketed Vehicles in this Area” to let users know what this is. - Mike
- [x] Edit drop down list descriptors ("make", "Weekday", etc) to more descriptive terms - Kiki 
- Example: Weekday Tab - Change “Weekday” to “Day of the Week” or “Make of Vehicle”, State to “State of License Plate”
- [x] Show error if date is out of range - Yen?
- [x] Show error if search location is out of range - Yen?
- [x] Fix Ticket Heuristics
- Change “Date” to “Ticket Date”
- Include a title – e.g. “Ticket Details” or “Info on this Citation” to let users know what this is.
- Fill in Make field with info or remove (It’s empty for every ticket).
- Consider links to info on Violation Types and Violation Codes (e.g.  link to more info on Yellow Zones, Code “80.56E2”, etc.)

### Resources
Wireframe can be found here: [Click me](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?node-id=135%3A7)

Excel to Heuristics can be found here:  [Click me](https://docs.google.com/spreadsheets/d/1cyEhiEKHTqfiZKik5DtVvf3aPmYv-9kzmX-7xn840Us/edit#gid=1081592578)

Power point for heuristic breakdown can be found here: [Click me](https://docs.google.com/presentation/d/10cOuppqzggkyqRw_d19lSxrtB-mUeqz_C790XoOe-yI/edit#slide=id.ge59ad16a7b_2_464)

**Comment by gordonruby** [comment]
@ymphan do you have any recent updates on this issue? Things like:

Progress: 
Blockers: 
Availability: 
ETA: 
Pictures (if necessary):
