### ISSUE TITLE
Automate the Server build  with Github Action

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#251]
### Overview
Current CICD build only deploy client. Server code needs automation

### Action Items
Add/build server to the existing yml

### Resources/Instructions
https://github.com/hackforla/lucky-parking/blob/master/.github/workflows/Continuous_Deployment_Client.yml

**Comment by simzou** [comment]
Blocked/Dependent on #252

**Comment by macho-catt** [comment]
Fixed in #330
