### ISSUE TITLE
write script to stop, rebuild, and restart server

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#252]
### Overview
Currently server needs manual work to build

### Action Items
create script to kill the process

**Comment by simzou** [comment]
Don't totally understand the details and scope of this issue from the title/description. Is it a script that kills the server, rebuilds it, and starts it again? Will the script be manually run on the server or is automating the deployment of the server part of this?

**Comment by qiqicodes** [comment]
Last week, we had to kill our server and rebuild the server. So we have the code for this issue. Currently the code is not part of the repo. 

We want to incorporate this before we automate with github action or other similar services

**Comment by macho-catt** [comment]
Modified version of the script is now saved under the server directory of the dev branch. The github action calls on the script everytime there is a new push on server files. Closing.
