### ISSUE TITLE
Add subheading to Lucky Parking Logo 

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#255]
### Overview
Need better placement of subheading for Lucky Parking Logo

### Action Items
Add subheading to Lucky Parking Logo "Avoid Parking Citations with Us" or "Find the Hotspot for Parking Citations"

### Resources/Instructions
Please work with Dash and Michael to see where the best location to place this subheading

**Comment by simzou** [comment]
I think the text and placement of this may be decided by the wireframes referenced in #268

**Comment by macho-catt** [comment]
Closing for now, the current heading is different from past design.
