### ISSUE TITLE
Change Type to Car Body Type under vehicles section

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#258]
### Overview
Unclear Reference

### Action Items
Change Type to Car Body Type under vehicles section

### Resources/Instructions
[UX Research and Next Steps](https://docs.google.com/presentation/d/10cOuppqzggkyqRw_d19lSxrtB-mUeqz_C790XoOe-yI/edit#slide=id.ge59ad16a7b_2_156)

**Comment by simzou** [comment]
This change is a sub task in #262
