### ISSUE TITLE
Decode Spell abbreviations under Type and Color. 

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#259]
### Overview
Current Coded Information is hard to understand at first glance

### Action Items
Decode Spell abbreviations under Type and Color. 
ie. GY to Grey, VN to Van, etc

### Resources/Instructions
[UX Research and Next Steps](https://docs.google.com/presentation/d/10cOuppqzggkyqRw_d19lSxrtB-mUeqz_C790XoOe-yI/edit#slide=id.ge59ad16a7b_2_156)

**Comment by macho-catt** [comment]
Some docs that have info (but doesn't encompass all abbreviations)
[DMV Body Types](https://www.dmv.ca.gov/portal/handbook/vehicle-industry-registration-procedures-manual-2/inquiries/chart-1-body-type-model-and-body-type-codes/)
[Color Codes for Plastics](https://www.ul.com/resources/color-codes-and-abbreviations-plastics-recognition)

**Comment by qiqicodes** [comment]
Here are more resources regarding car body style / type abbreviation, and color code
* [Arizona Department of Transportation - T & R Body Styles/ Category Codes](https://azdot.gov/sites/default/files/2019/06/tr-body-styles-category-codes.pdf)
* [Wisconsin Department of Transportation - Vehicle Color and Abbreviation](https://wisconsindot.gov/Pages/dmv/vehicles/title-plates/veh-color-abbrev.aspx)
* [DMV Body Style Abbreviation List](http://www.dhs.state.or.us/spd/tools/field/DMV%20codes.pdf)
* [Fox Valley Technically College - Vehicle Color and Abbreviation](https://www.fvtclearninginnovations.com/FoxCity/Forms/Abbreviations#VehicleAbbreviations)
