### ISSUE TITLE
Change Make to Make of Vehicle

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#261]
### Overview
Unclear Label

### Action Items
Change Make to Make of Vehicle

### Resources/Instructions
[UX Research and Next Steps](https://docs.google.com/presentation/d/10cOuppqzggkyqRw_d19lSxrtB-mUeqz_C790XoOe-yI/edit#slide=id.ge59ad16a7b_2_156)

**Comment by simzou** [comment]
This label change is a sub task of #262
