### ISSUE TITLE
Select data with "Zip Code" feature 

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#266]
### Overview
current app uses polygon draw, it is good to include a zip code selection feature

### Action Items
- [x] Adding zip code layer to mapbox
- [x] Feeding zip code coordinates to polygon draw feature

**Comment by mg78856** [comment]
- Some zip codes currently do not work with the request header capacity as the polygon coordinates are too large (431 error). Example: (zip: 90005)/Koreatown, CA
- Need new sql query that requires less header space. Looking into `ST_GeomFromWKB()` or using zip code to select geometry.
- Also some zip codes need to have selection disabled as they do not contain any data (being outside LA jurisdiction) and only highlight tickets of bordering zip codes within LA's jurisdiction. Example: (zip: 90211)/Beverly Hills, CA

Current query:

``SELECT ST_AsGeoJSON(geometry) FROM test1 WHERE ST_Contains(ST_GeomFromGeoJSON('{
          "type":"Polygon",
          "coordinates": [${polygon}],
          "crs": {"type": "name", "properties": {"name": "EPSG:4326"}}										                            
        }'), test1.geometry) LIMIT 30000;``
