### ISSUE TITLE
Incorporate linters for the backend code

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#271]
### Overview
We need to incorporate linters for the backend code to unify styling and minimize code errors.

### Action Items
- [x] Discuss with the team / lead the rules we want to incorporate. Airbnb style guide is a good contender.
- [x] Research and implement the following for the backend code
   - [x] ESLint
   - [x] Prettier
   - [x] Husky
   - [x] Lint-Staged
- [x] Go through each file in the backend and run the linter, correcting any errors
- [x] Ensure that the website still functions as intended after the linting change

### Resource
[Airbnb Style Guide](https://github.com/airbnb/javascript/tree/master/react)

**Comment by simzou** [comment]
Instructions for adding a pre-commit git hook that formats code: : https://javascript.plainenglish.io/how-to-automatically-format-your-code-before-pushing-to-the-remote-server-a5ace1dc2fa7
