### ISSUE TITLE
[DRAFT] Date range selector UI/UX issues/improvements

### ISSUE THREAD

**Issue by simzou** [hackforla/lucky-parking#273]
These could (and probably should) be separated out into different issues but capturing the problems I've found with the date selector in one place for now

- Current defaults for the date range selector start and end are both the current day though the map view shows all the data so there's a mismatch. Would be better if it's just left blank. The 311 project has some nice presets as well [here](https://www.311-data.org/data)
- There should be some indication as to what dates we have data for. Either enforced by the date range selector or just displayed as helper text
- The date range selector should work more like flight websites, Airbnb, hotels, etc. where the start and end date selector are chosen in the same interface as opposed to selected separately.
- The end date should be restricted such that you can't go past the current date
- If you select a specific time of day in the search, it doesn't show up in the search box
- There should be a button like "Filter" or something to let the user initiate the date range search. Right now it happens automatically and then a deactivate (soon to be reset) button shows up

**Comment by simzou** [comment]
The existing library allows us to do [this](https://reactdatepicker.com/#example-date-range-for-one-datepicker)

There's also [this one](https://hypeserver.github.io/react-date-range/#daterangepicker) specifically for picking date ranges which I think looks a tad nicer but may not have as many options.

**Comment by macho-catt** [comment]
Progress: Just picked up and going to start to fix the date range
Blockers: n/a
Availability: 4 hours
ETA: By next Sunday
Pictures (if necessary): n/a

**Comment by macho-catt** [comment]
Progress: Was busy with interviewing the past two weeks, so did not have time to work on this. 
Blockers: n/a
Availability: 4 hours
ETA: By next Sunday
Pictures (if necessary): n/a

**Comment by gordonruby** [comment]
Simon, can you rewrite this issue for more context please?

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by gordonruby** [comment]
.. @macho-catt Is this issue still in progress?
