### ISSUE TITLE
Should we Merge Pull Request, Squash and Merge or Rebase and Merge

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#276]
### Overview
What is our preferred way to merge pull request? We should discuss figure out the best merge for our project going forward

### Action Items
- [ ] ~~Merge Pull Request~~
- [x] Squash and Merge 
- [ ] ~~Rebase and Merge~~

**Comment by nc-aura** [comment]
What you guys think about?  Merge PR would be thorough, squash is clean.  feel like for the current stage. squash is good enough.

**Comment by simzou** [comment]
I lean toward squash and merge as well. Think our issues are generally small enough that the code changes should be digestible. Rebase has been explained to me probably a half dozen times now and it is a deep source of shame that I still don't totally grok it 🤷

**Comment by mg78856** [comment]
I've only ever done merge through PR but if you guys want squash we can do that too. Don't have a preference.

**Comment by qiqicodes** [comment]
I lean toward squash and merge ☺️

**Comment by simzou** [comment]
Cool, decision/consensus reached! @mg78856 to clarify we would still be doing merges through PRs, these are just the three options GitHub gives us when we press the button.

**Comment by simzou** [comment]
Reopening pending update to the wiki about this decision.

**Comment by qiqicodes** [comment]
Feel free to read this pull request guide and add anything you feel applicable to the guide. Current guide has the PR workflow and the checklist.

[How to Review Pull Requests](https://github.com/hackforla/lucky-parking/wiki/How-to-Review-Pull-Requests)
