### ISSUE TITLE
[DRAFT] Add a legend on the map

### ISSUE THREAD

**Issue by eugenecha** [hackforla/lucky-parking#286]
### Overview
We need a legend on the map. It could either be a hover over legend, or a fixed one that stays on the bottom of the map. 

### Action Items
- [ ] Add a legend on the map

### Resources/Instructions
[Figma wireframe](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?node-id=135%3A7)

**Comment by gordonruby** [comment]
@eugenecha, before this and other new issues can move into the Prioritized Backlog, I'd love to understand more context about them to really know what's important and what's at stake as we try to prioritize. It's why I changed the title of this issue to include DRAFT. 

Can you please update the Overview of this and other new issues to match the new template for Lucky parking?

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
