### ISSUE TITLE
Change chart style

### ISSUE THREAD

**Issue by eugenecha** [hackforla/lucky-parking#287]
### Overview
There are just too many slices, and the small slices can be difficult to read and color distinctly. 

### Action Items
Switch to bar charts. 

### Resources/Instructions
[Figma wireframe](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?node-id=135%3A7)

**Comment by simzou** [comment]
Closing as duplicate of #267
