### ISSUE TITLE
Codebase refactoring

### ISSUE THREAD

**Issue by simzou** [hackforla/lucky-parking#302]
### Overview
In working with this codebase, @qiqicodes and I have discussed some refactoring we'd like to do. Some of it is still fuzzy and requires more investigation. But there are some major items already and more will be added in the comments as we decide on them. We're tentatively planning to discuss this issue with the dev team next week

### Action Items
- [x] Implement a new dev branch and dev instance so changes are made in this new branch 
- [x] Refactor the structure of the backend code to ease its maintainability in the future
    - Add new modules / middleware as necessary
    - [x] Modify promises to use async / await structure
- [ ] Refactor the structure of the frontend code to ease its maintainability in the future
    - [ ] Use tailwinds instead of scss for our css framework
    - [ ] Abstract maps.js code even further
    - [ ] Update Redux to use the latest version / syntactic sugar
- [ ] Once code is satisfactory on both front and back ends, create a release branch to integrate to the master branch (production)

### Resources/Instructions
- Comment on above list or add more. Eventually prioritize and make separate issues for the stuff that seems most important / interesting.

**Comment by macho-catt** [comment]
I also created a new issue #316.
When we start doing the codebase refactoring. it might be a smart idea to have a separate dev and prod branches so that any changes that may break the app won't need to be pushed to the production branch immediately. We can fix any bugs in the dev branch and ensure it is stable before pushing to production. Just a thought.

**Comment by macho-catt** [comment]
The backend code under the dev branch has been restructured. New modules / middleware will be added to it as necessary.
The frontend is currently being restructured as well.

**Comment by macho-catt** [comment]
A release branch was created to merge updates on dev back to master.
PR: #362
Frontend dev is still being worked on by @glenflorendo

**Comment by glenflorendo** [comment]
> * [ ]  Refactor the structure of the frontend code to ease its maintainability in the future
>   * [ ]  Use tailwinds instead of scss for our css framework
>   * [ ]  Abstract maps.js code even further
>   * [ ]  Update Redux to use the latest version / syntactic sugar

Good progress has been made with the front-end refactor.
Majority of the UI elements have been recreated with TailwindCSS and the map code is now more maintainable.
Most of the remaining work is on implementing data management with Redux / React contexts.

**Comment by gordonruby** [comment]
@macho-catt is it possible that this issue is on hold, since no one is assigned to it? I'm tempted to move it back to the prioritized backlog. Thoughts?

**Comment by macho-catt** [comment]
@gordonruby glen should be assigned to this issue
