### ISSUE TITLE
React Datepicker "January" Month Option Bug

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#307]
### Overview
Current Datepicker month option is buggy when selecting "January" option. If click January as first option, month registers as user's machine's date.

There is a workaround to get January to work. Select other month option before selecting "January" will properly select "January".

<details>
<summary>Datepicker Bug</summary>
<img src="https://user-images.githubusercontent.com/68657634/135982807-dc5aa482-820b-438a-8534-9589bc04da8c.gif">
</details>

<details>
<summary>Datepicker Current Workaround</summary>
<img src="https://user-images.githubusercontent.com/68657634/135982791-2c96d3b4-3837-4145-b714-86d8105bb82b.gif">
</details>

### Action Items
- [ ] Fix React Datepicker's "January" option

### Resources/Instructions
* [React Datepicker npm](https://www.npmjs.com/package/react-datepicker)
* [React Datepicker examples](https://reactdatepicker.com/)

**Comment by macho-catt** [comment]
Closing because this is fixed in #314
