### ISSUE TITLE
Create Project card for Lucky Parking

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/lucky-parking#37]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [ ]   Gather items
  - [ ]  600 x 400 image
  - [ ]  Alt image text
  - [ ]  Name of project
  - [ ]  A blurb about your project
  - [ ]  Links (website, github, demo, etc. )
  - [ ]  What you are looking for skills wise
  - [ ]  Partner(s)
  - [ ] Tools (section to display the tools being used for the project (Ex: figma, Balsamiq, photoshop, etc.)
  - [ ] Banner image to be displayed on Project Home Page at 1500 x 700 px
  - [ ] Any resources for a Getting Started link (either a link to a wiki or readme)
- [ ]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by charlottesauce** [comment]
###  600 x 400 image
![lucky-parking-project](https://user-images.githubusercontent.com/45779646/74081298-51252400-4a02-11ea-8547-540391aea59b.png)

### Alt image text
Parking sign emitting a signal which also resembles a rainbow. 

###  Banner image to be displayed on Project Home Page at 1500 x 700 px
![Lucky Parking Hero](https://user-images.githubusercontent.com/45779646/74081316-7a45b480-4a02-11ea-8e97-2ab462b08532.png)

**Comment by breeze-094** [comment]
Thanks so much for the proactive work! 
I realized if the hero image would be a street parking context would be more relevant within the same style :) how would you think?
