### ISSUE TITLE
Transfer Domain to Org

### ISSUE THREAD

**Issue by MichelleRT** [hackforla/lucky-parking#379]
### Overview
We need to ask Simon to help transfer the domain luckyparking.org to the organization. 

### Action Items
- [x] Ask Simon to review the documentation for transferring the domain https://support.google.com/domains/answer/3251236?hl=en&ref_topic=9003137
- [x] Ask Simon if he can join a PM/Org meeting
- [ ] Ask Bonnie to complete the transfer

### Resources/Instructions
- Google documentation for transferring domains: https://support.google.com/domains/answer/3251236?hl=en&ref_topic=9003137
- Domain: http://www.luckyparking.org/
- LP: PM/Org's Agenda Issue https://github.com/hackforla/lucky-parking/issues/354

**Comment by gordonruby** [comment]
@ExperimentsInHonesty it looks like this issue is DONE based on my ability to access: http://www.luckyparking.org/ Would you agree? If so, I'd be happy to close this issue. @simzou is this related to work that we were doing with you?

**Comment by gregpawin** [comment]
Simon did transfer the domain luckyparking.org to Bonnie.
