### ISSUE TITLE
Split citation data into three categories and output three csv files

### ISSUE THREAD

**Issue by breeze-094** [hackforla/lucky-parking#39]
### Overview
since we separate the citation data into three different models, it is better to separate into three data sets and do the data cleaning work. 
### Action Items
Split citation data into three categories (top three citations reasons)and output three csv files. 

### Resources/Instructions
Categories are: 
1.Street Sweeping / No Parking
2.Meter Expiration
3.The rest include Red Zone / White Zone etc.

Use csv file "Simplified Citation After 2015 July to 2019.csv" to start work. 
Here is the link on Gdrive to download: https://drive.google.com/file/d/1IEWhjyOa_xGDhjnws2vMGG_53TM2dLOO/view?usp=sharing
Put output data file on Github and Google drive folder as well.

**Comment by tabatahg** [comment]
I can tackle this. I'll try to finish this my Monday
