### ISSUE TITLE
Create new project card for Lucky Parking

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/lucky-parking#40]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [ ]   Gather items
  - [x]  600 x 400 image
      - [x]  Alt image text
  - [ ]  Hero image to be displayed on Project Home Page at 1500 x 700 px
      - [ ]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (website, github, etc.)
  - [x]  What you are looking for skills wise
  - [ ]  Partner(s)
  - [x]  Location
  - [x]  Readme
- [ ]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

Here is their info
Name of Project: Lucky Parking
Blurb: A platform looking for nearby street parking with least possibility of getting citation
Tools: Google Colab and its dependency
Looking for: Python, App Development, Machine Learning, Deep learning, Data Science.
Links: github https://github.com/hackforla/lucky-parking 
Readme: https://github.com/hackforla/lucky-parking/blob/master/README.md
Location: Santa Monica

**Comment by ExperimentsInHonesty** [comment]
@breeze-094 Please provide an update:
1. Progress
2. Blocks (what might be an obstacle that keeps you from completing this e.g., lack of that skill on your team, time availability, etc.)
3. Availability 
4. ETA for completion

**Comment by breeze-094** [comment]
Hi Bonnie, 

Thank you very much for checking up !

Here is the answer: 

1. Progress: 

ON 2ND PHASE of now. There should be multiple sections running parallel on this phase.

Section 1: Street Sweeping / No Parking.
DONE - Research to confirm the statement "Street Sweeping / No Parking: percentage is close to 100% after certain time once it started." is accurate. 
UNDONE - Layout on map/app regarding the street sweeping regulations by segment.

Section 2: Meter Expiration.  
UNDONE - Use machine learning supervised model Logistic Regression to implement. It is considered binary classification problem (Logistic Regression recommended)
UNDONE - Divide the dataset into training and validation categories, compare between the prediction and validation data.

Section3: Red Zone / White Zone etc. 
3.a. If consider this is a Linear Regression model:
IN PROGRESS - Implement Random Forest model 
UNDONE - Implement SVM (Support Vector Machine), Decision Tree.
UNDONE - Validate if the citation pattern remain the same from 2015, 2016, 2017, 2018, 2019. Then we can use the first three year date for training,  and last year data for validating. 

3.b. consider this is a Binary Classification model:
UNDONE - Add the positive data regarding where and when there is no citation
UNDONE - Use Logistic Regress to perform binary classification

3RD PHASE overall not start yet. 
CAN DO NOW - Further research of implementation 
CAN DO NOW - Layout available street parking on website and app. 
CAN DO NOW - Project scope of work to be update regarding combination of phase two and phase three. 


2. Block.

- Lack of experienced data scientists who are good at implementing multiple machine learning models to get accurate prediction. 
- Lack of experience web developer / app-developer who are good at layout the current available data into user-friendly, interactive visual information  in real-time. 
- Lack of experienced project manager who are good at communicating / collaborating with existing available resources 
- Lack of experience of UI/UX designer who are good at on how the app will be interacting with users effectively. 


3. Availability. 

-  Clear scope of work. (Phase 3 still need to be refined as project move forward) 
- General level of data scientist who can perform general machine learning model but cannot get accurate number. 
- Good start  design of logo and hero image. 
- A great mount of volunteers who are eager to learn and help but need better technical leads. 
- Good communication environment on Slack and Good drive. 

4.  ETA for completion(estimated) 
Phase 2: Three months more
Phase 3: Three months

**Comment by harishlingam** [comment]
@charlottesauce Please let us know where you are with the hero image. Thanks!

**Comment by breeze-094** [comment]
Hi Harish: 
here the logo
![lucky-parking logo](https://user-images.githubusercontent.com/45272158/75748828-3bd7a880-5cd5-11ea-95fc-0352db5cf782.png)
and here is hero
![Lucky Parking Hero](https://user-images.githubusercontent.com/45272158/75748844-43974d00-5cd5-11ea-9edf-0a0a409a5f3a.png)

**Comment by cnk** [comment]
New card will go to website when project leadership updates are merged

**Comment by harishlingam** [comment]
Rong provided a revised list of open roles. Please update project card:

Frontend Software Engineer, Backend Software Engineer, Advanced Data Scientist, Python Enthusiast
