### ISSUE TITLE
Build date picker

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/lucky-parking#443]
### User Story

As a developer, I want a modular date picker component, so I can easily implement date filtering.

### Description

The UX team has designed a data picker / calendar. We need this to be built in the UI library using React and TailwindCSS.

### Acceptance Criteria

- [ ] Build date picker component

### Design References

- [Figma Design](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?type=design&node-id=5142-68002&t=3T8U68NTX4cOM6WT-0)

**Comment by gibsonliketheguitar** [comment]
@glenflorendo I would like to claim this task
