### ISSUE TITLE
Screen Flows

### ISSUE THREAD

**Issue by mklmrgn** [hackforla/lucky-parking#461]
### Overview
Creating Screen Flows to show developers, new designers, and stakeholders how the different features work and flow together. Uses the [Autoflow](https://www.figma.com/file/CeAEESvVySGqCxbKNmUzIv/Autoflow-(Community)?node-id=0%3A1&t=ZxffaSDVr1PPtcT2-1) plug-in for Figma.

The Figma page can be found [here.](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?node-id=731%3A251&t=lJZZAPbzmHXMdspJ-1)

### Action Items
Only last step for Dev (provide feedback)

- [ ] Create consistency of flows 
- [ ] Finish Single Data flows
- [ ] Finish Compare Mode flows
- [x] Get feedback from Devs (is it understandable?)

**Comment by glenflorendo** [comment]
@mklmrgn How would you like me to provide feedback for this?

**Comment by glenflorendo** [comment]
@mklmrgn I added some comments and questions for clarification. Some of these will probably need to be a joint decision with product.

**Comment by mklmrgn** [comment]
Thanks Glen. I’ll take a look at these. It’s kind of a crazy day, so I may not get to it today. Are you at the meeting tonight? I may not be able to attend, but should be able to drop into the next dev meeting if anything needs a more detailed discussion.Thanks!Mike Sent from my iPhoneOn Mar 19, 2023, at 7:52 PM, Glen Paul Florendo ***@***.***> wrote:﻿
@mklmrgn I added some comments and questions for clarification. Some of these will probably need to be a joint decision with product.

**Comment by glenflorendo** [comment]
@mklmrgn I went through your replies! Appreciate your going through it!
Looks like we still have some stuff to go over with @gregpawin and @dannycpham.
