### ISSUE TITLE
Create "How it Works" Pop-up

### ISSUE THREAD

**Issue by mklmrgn** [hackforla/lucky-parking#462]
### Overview
Finish HiFi Pop-up that explains to users how the site works. 

### Action Items
- [ ] Finalize HiFi Design for pop-up (clicking on How it Works button in Nav)
- [ ] Create a component on the components Figma page

**Comment by mklmrgn** [comment]
Complete @glenflorendo @dannycpham @gregpawin 

<img width="996" alt="Screen Shot 2023-07-13 at 12 35 18 PM" src="https://github.com/hackforla/lucky-parking/assets/81997978/343ec510-044f-4c37-bee2-f102af10fdd0">

It's under "How it Works" on the Flows page
https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?type=design&node-id=731%3A251&mode=design&t=ircwEQAclpIWE3yH-1

On the Prototype Newest page, you can use the "How it Works Flow" if you want to use the prototype feature.
https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?type=design&node-id=731%3A243&mode=design&t=ircwEQAclpIWE3yH-1

**Comment by dannycpham** [comment]
@mklmrgn I am going to mark this as done since development has been finished on this ticket per issue number #535
