### ISSUE TITLE
Fix the bug of Coordinate transformation 

### ISSUE THREAD

**Issue by breeze-094** [hackforla/lucky-parking#48]
### Overview
Previously, when transform the coordinates from NAD 1983 to world coordinates system(Google map compatible) will lost 1 million data. 

### Action Items
PLEASE fix the bug so that the data loss is as less as possible 

### Resources/Instructions
Review the Google colab file [here](https://drive.google.com/open?id=1Nh9HT5XbZsavFSL0HWaeNxiNnEr7c9e3) and submit your improved code of transformation.

**Comment by gregpawin** [comment]
I've cleaned up the code a little bit. Breeze can you check that this works for you? I can't get the figure to display on my end.
[coord_conversion.zip](https://github.com/hackforla/lucky-parking/files/4339333/coord_conversion.zip)
