### ISSUE TITLE
[Defect]: Missing Zip Codes in Geosearch

### ISSUE THREAD

**Issue by dannycpham** [hackforla/lucky-parking#490]
### Environment

Local on Windows

### Steps to Reproduce

1. Run application locally
2. Type in 90024 in the search field
3. It does not appear in the results list.
4. Typing any other zip codes results in the same 5 results (90045, 90028, 90015, 90012, 90069)

### Expected Behavior

When I typed in 90024 into the search field, I expected 90024 to be shown at the top of the results list. 

### Actual Behavior

When I type in 90024, it does not appear in the results list and the same 5 results that initially appeared are still present.

**Comment by dannycpham** [comment]
I think this is buggy for other aspects of the geocoder, not just for zip codes. Locations are not populating with other keywords as well.

**Comment by eulloa10** [comment]
@glenflorendo are you already working on this issue? If not, can I look into it?

**Comment by glenflorendo** [comment]
> @glenflorendo are you already working on this issue? If not, can I look into it?

I have started working on this, but totally fine by me if you want to work on it!

I'll reassign this to you. Let me know if you need any help. :)
