### ISSUE TITLE
Load sample data in database

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/lucky-parking#494]
### User Story

As a developer, I want sample data in the database, so I can properly implement an API to query data for the website.

### Description

We have a free-tier MongoDB instance with no data.

We should take a subset of the citation data and insert it into the database (January 2021 - December 2022).

Design an ERD for the data (an ERD is helpful, even for a NoSQL database), so we know the structure of the data.

### Acceptance Criteria

1. Design an ERD.
2. Insert the sample data into the database.
3. Write documentation.

### Technical References

- [Parking Citation dataset](https://data.lacity.org/Transportation/Parking-Citations/wjz9-h9np)
- Reach out to @glenflorendo for database access

**Comment by glenflorendo** [comment]
Hi, @nicolettedmabeza! How is your progress on loading the sample data to the database? I've seen your ERD and documentation for this, which are great!

**Comment by nicolettedmabeza** [comment]
Hi @glenflorendo ! Sorry for the delay but I have updated the sample data to the database as requested.

**Comment by glenflorendo** [comment]
@dannycpham, increasing points for this as I failed to consider the work involved in loading the data into the database.

**Comment by glenflorendo** [comment]
The MongoDB now has a sample data size of 600,000 documents: 50,000 per month for 2022.
