### ISSUE TITLE
Set up initial unit testing framework

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/lucky-parking#499]
### User Story

As a developer], I want to have a unit testing framework , so that I can write robust tests to ensure my code is working as intended.

### Description

Since our code is mostly TypeScript and React, we will use Jest and React Testing Library.

### Acceptance Criteria

- [ ] Install Jest and React Testing Library
- [ ] Set up Jest
  - At the very least, we need a coverage report to be generated every time Jest is run
- [ ] Choose one file in the `website` package and write tests for it as a starting point
  - Try to reach a 100% coverage for this file

### Technical References

- [Jest](https://jestjs.io/)
- [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

**Comment by gibsonliketheguitar** [comment]
@glenflorendo I'd like to claim this task too
