### ISSUE TITLE
Using CNN(Convolution Neural Network) & GLN to improve prediction accuracy 

### ISSUE THREAD

**Issue by breeze-094** [hackforla/lucky-parking#50]
### Overview
Use CNN(Convolution Neural Network) & GLN to improve predict the accuracy of probability patrol officer’s occurrence related to time and location.

### Action Items
Use CNN(Convolution Neural Network) & GLN to improve predict the accuracy of probability patrol officer’s occurrence related to time and location.

### Resources/Instructions
CNN is good at time stamp machine learning
This time:
- Use the full data set. click [here](https://drive.google.com/open?id=1c4c4m8dW1oHiPS3iXF9CT-C5akz6SA2p) to download full entry.
- convert lat & long into zipcode, try as many zip code as possible. you can acceess zip code on github under data folder or click [here](https://github.com/hackforla/lucky-parking/tree/master/data/CAMS_ZIPCODE_STREET_SPECIFIC)
- Check out president code on Github 

- [ ] [Random Forest_zip code.ipynb](https://github.com/hackforla/lucky-parking/blob/master/notebooks/Random%20Forest_zip%20code.ipynb)
- [ ] [one-hot encode_DNN2.ipynb](https://github.com/hackforla/lucky-parking/blob/master/notebooks/one-hot%20encode_DNN2.ipynb)

**Comment by ldaws003** [comment]
Hi breeze, has someone started work on this?

**Comment by breeze-094** [comment]
not yet. it is a good task. we can discussed today and see how to moveforward
