### ISSUE TITLE
Drawing: Drawing UI

### ISSUE THREAD

**Issue by dannycpham** [hackforla/lucky-parking#516]
### User Story

As a user, I want to be able to filter data down to a more granular level to visually see citation data for a region and time frame.

### Description

When a user clicks on the “Draw Boundary” button, a new UI would appear. 

The region type would be labeled as “Custom Draw”

Text in the textual search would be “Draw or search locations to focus the map.”

The user should see a gray UI in the top middle of the map with the text, “Draw a shape around the area you want data on.” This same UI bar should have an Apply and Clear button.

This UI gray bar should not shift as the user zooms in and out around the map.

This UI gray bar should be responsive to browsers width to accommodate different resolutions.

Clickability of the Apply and Clear button is out of scope for this ticket. Drawing capability is out of scope for this ticket.

### Acceptance Criteria

1. If a user selects Draw Boundary, then the user would see a new UI appear specifically for Custom draws.

### Design References

[Figma](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?type=design&node-id=731-243&mode=design&t=O6uPiQpCRAKlc3Yd-0)

**Comment by glenflorendo** [comment]
This ticket is saved for Aliya.

**Comment by glenflorendo** [comment]
@kevykim Any updates on your progress on this ticket? Any blockers?

**Comment by dannycpham** [comment]
@kevykim Hello, we haven't had progress on this for a while now, so I will reassign this. Please let us know when you are available, and we can reallocate work to you. Thank you!
