### ISSUE TITLE
Drawing: Drawing UI Interactions

### ISSUE THREAD

**Issue by dannycpham** [hackforla/lucky-parking#518]
### User Story

As a user, I expect certain actions to occur when I interact on the new drawing UI. I want to be able to filter out my data on a more granular level using interactions on this drawing UI.

### Description

As a user, they would expect certain actions to occur when they click on the “Apply” button, the “Clear” button, and data input in the text field.

When the user first sees the drawing UI, both the “Apply” and “Clear” buttons would be gray and not selectable.

A user is able to search for a specific area to focus their drawing. They are able to type in the text field for areas or zip codes to isolate the specific areas, and the map would appropriately zoom in closer to whatever the area is.

If and only if the user has begun drawing something on the map, would the buttons Apply and Clear become clickable for the user.

When the user clicks on the “Clear” button, whatever the user has drawn thus far on the map would be erased. Once the drawing has been erased, both the “Apply” and “Clear” would be grayed out and become unclickable again.

When a user clicks on the “Apply” button, the area in which the user has drawn would be selected and the data would be applied to only that specific area. If the drawing that the user has created is not directly connected between the two end points, the system would automatically complete and connect the two end points, so the data can be pulled in correctly.

When the user has successfully clicked on the “Apply” button, Citation Types, Date Range, Calendar, and graphs would appear. 

### Acceptance Criteria

1. If a user has clicked on Clear, then the drawing would be erased and the drawing UI would be reset.
2. If a user has clicked on Apply, then the data would be shown in a graph with further selections available for the user through Citation Types, Date Ranges, and Calendars.
3. If a user has clicked on Apply while the drawing is not completely connected, then the system would automatically connect the two endpoints for ease of use for the user.

### Design References

[Figma](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?type=design&node-id=731-243&mode=design&t=O6uPiQpCRAKlc3Yd-0)

**Comment by glenflorendo** [comment]
Blocked by #516
