### ISSUE TITLE
Build progress stepper

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/lucky-parking#521]
### User Story

As a developer, I want a modular progress stepper component, so I can easily display progress bars for each step a user needs to perform.

### Description

The UX team has designed a progress stepper. We need this to be built in the UI library using React and TailwindCSS.

### Acceptance Criteria

- [ ] Build progress stepper component in the`ui` package

### Design References

- [Figma Design](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?type=design&node-id=3203-29829&mode=design&t=kuTqDTEYH3dXWSan-0)

### Technical References

- [TailwindCSS Docs](https://tailwindcss.com/)

**Comment by dannycpham** [comment]
@melaniecheung Hello! Any updates on your progress on this ticket? Any blockers?

**Comment by glenflorendo** [comment]
@dannycpham I spoke with @melaniecheung who is currently out on vacation. We can unassign for now. :)
