### ISSUE TITLE
Build picklist

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/lucky-parking#522]
### User Story

As a developer, I want a modular picklist component, so I can easily create different controls with preset values for users to choose from.

### Description

The UI/UX team has a picklist in their designs. We need this to be built in the UI library using React and TailwindCSS.

### Acceptance Criteria

- [ ] Build picklist component in the`ui` package

### Design References

- [Figma Design](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?type=design&node-id=5102-71376&mode=design&t=kuTqDTEYH3dXWSan-0)

### Technical References

- [TailwindCSS Docs](https://tailwindcss.com/)

**Comment by glenflorendo** [comment]
@one2code Any updates on your progress on this ticket? Any blockers?

**Comment by dannycpham** [comment]
@one2code Hello, we haven't had progress on this for a while now, so I will reassign this. Please let us know when you are available, and we can reallocate work to you. Thank you!

**Comment by gibsonliketheguitar** [comment]
Assigning task to myself. #508 Implemented a select option in [Calendar Component](https://github.com/hackforla/lucky-parking/blob/9cd33bf344bc1e7c65fca65cdbd3498c20404c62/packages/ui/src/components/calendar/calendar-select.tsx#L27)

We can just rip it out of calendar component.
