### ISSUE TITLE
Implement citation service

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/lucky-parking#557]
### User Story

As a developer, I want a citations service to handle all work involving citations.

### Description

In the manager/worker analogy, the controllers are the manager and the the services are the workers.
The controller receives the work to be done, decides which services should perform the work, then passes the work to be completed. The services actually take that work and complete it.

On a high level, the POST `citation` endpoint takes in different filters (dates, geometry, etc.) to be used to find and return a list of parking citations.

At this point, the citation service will only have one operation, which is to query the database to find a list of parking citations that adhere to some filters (dates, geometry, etc.).

### Acceptance Criteria

1. The citation service has an operation to query the database for a list of parking citations.
2. The documentation should be updated, if necessary.

### Design References

N/A

### Technical References

N/A

### Additional Information

N/A

**Comment by gibsonliketheguitar** [comment]
@glenflorendo  should I be referencing the API doc bellow?

https://github.com/hackforla/lucky-parking/blob/885769d7bf85106419f081e6092969cca33bb547/packages/api-express/docs/specs-v1.yaml#L22-L57

**Comment by glenflorendo** [comment]
@gibsonliketheguitar Yes, for both #552 and this ticket, the API specifications should be followed and updated, accordingly.
