### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by mklmrgn** [hackforla/lucky-parking#616]
### Overview

UX/UI to create loading screen feature

### Action Items

- UX/UI Creates Prototype for Loading Screen
- Dev will try out prototype and offer any feedback and sign off

### Additional Information

You can demo the prototype and use the "loading screen" flow to see how it works!
https://www.figma.com/proto/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?page-id=731%3A243&type=design&node-id=6478-39941&viewport=438%2C-445%2C0.05&t=zMvTCeFGnkh5cGNl-1&scaling=min-zoom&starting-point-node-id=6478%3A39920&show-proto-sidebar=1&mode=design
<img width="774" alt="Screen Shot 2024-02-05 at 6 01 55 PM" src="https://github.com/hackforla/lucky-parking/assets/81997978/f7486e1a-1207-42f3-80bb-d7bbdad9f404">

**Comment by glenflorendo** [comment]
@mklmrgn It looks great! Thanks for the prototype.

@dannycpham This is technically feasible. Anything to note as product before we allocate resources to this ticket?

**Comment by dannycpham** [comment]
@glenflorendo  This seems fine to implement. My one concern is mobile. Are we trying to implement this just for Desktop side for now and figure out the responsive nature of it for mobile later? I can see potential scaling issues in the future for mobile and other small screen sizes.

**Comment by glenflorendo** [comment]
> @glenflorendo This seems fine to implement. My one concern is mobile. Are we trying to implement this just for Desktop side for now and figure out the responsive nature of it for mobile later? I can see potential scaling issues in the future for mobile and other small screen sizes.

Desktop for now. We'll do mobile responsive as a priority after or right before launch.

**Comment by glenflorendo** [comment]
With design and product sign-off, this is ready for development. Engineering will take over this ticket now.
