### ISSUE TITLE
[CICD] Create compliance workflow

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/lucky-parking#636]
### User Story

As a developer, I want to make sure we automate our compliance policies, so that we can easily manage/handle compliance issues.

### Description

Create a new GitHub Action workflow in `.github/workflows/compliance.yaml`.

In this initial ticket, we want to make sure all pull requests are linked to an issue. If not, a comment will be posted to the pull request, tagging the author, to include a linked issue following GitHub conventions.

### Acceptance Criteria

- [x] The file `.github/workflows/compliance.yaml` is created.
- [x] The compliance workflow runs every time a pull request is created, edited, reopened, etc.
- [x] The compliance workflow checks that the pull request is linked to an issue.
- [x] The compliance workflow posts a message if the pull request is not linked to an issue.

### Technical References

- [open-sauced's compliance workflow](https://github.com/open-sauced/open-sauced/blob/main/.github/workflows/compliance.yml)
- [GitHub Docs: Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by t-will-gillis** [comment]
Hi @glenflorendo -
- Regarding trigger `types`: the default triggers are PR `opened`, `synchronize`, and `reopened` and "open-sauced" adds `edited`. Which of the additional triggers such as `(un-)labeled`, `(un-)assigned`, etc might we also want?
-  Can/ should this workflow follow a pattern similar to the Website workflows? For example, creating a `/github-actions/` folder with js files supporting the workflow? (Just noticing that many of the Website workflows come from your commits 2 + years ago)

**Comment by glenflorendo** [comment]
> * Regarding trigger `types`: the default triggers are PR `opened`, `synchronize`, and `reopened` and "open-sauced" adds `edited`. Which of the additional triggers such as `(un-)labeled`, `(un-)assigned`, etc might we also want?

Good question. Let's also include `unassigned`.

> * Can/ should this workflow follow a pattern similar to the Website workflows? For example, creating a `/github-actions/` folder with js files supporting the workflow? (Just noticing that many of the Website workflows come from your commits 2 + years ago)

Let's aim to do things as simply as possible first. If we can't accomplish what we want, then we can have a helper files. We can store these in the same folder as the workflows.

**Comment by t-will-gillis** [comment]
Update 3/30/24: 
`compliance.yaml` ready for final testing. ETA for completion 3/31/24
