### ISSUE TITLE
Apply GLN (Global Location Number) on Prediction of Patrol officer nearby 

### ISSUE THREAD

**Issue by breeze-094** [hackforla/lucky-parking#81]
### Overview
Apply GLN (Global Location Number) on Prediction of Patrol officer nearby 

### Action Items
Research and try to figure out apply GLN (Global Location Number) on Prediction of Patrol officer nearby.

### Resources/Instructions
For Virtual zip code, refer to below: 
- Open Location Code
- Google plus code
- what 3 words
- DDN: Digital location number
- Fractal Coding 

Find one of them most handy for you and further develop it on how we can group our project via virtual zip-code

**Comment by zephmann** [comment]
I think open location codes would be good.

https://towardsdatascience.com/plus-codes-open-location-code-and-scripting-in-google-bigquery-30b7278f3495

Should be simple to generate and add the codes from the lat / long.

https://github.com/google/open-location-code/tree/master/python
https://github.com/google/open-location-code/blob/master/python/openlocationcode/openlocationcode.py

**Comment by breeze-094** [comment]
@zephmann can you work with Leon @ldaws003 to see how it will help on the DNN or CNN prediction model?
